#!/usr/bin/env bash
# bulk-push-docs.sh — pushea docs-system/ a GitHub en múltiples repos
#
# Uso:
#   bash bulk-push-docs.sh --repos-file repos.txt
#   bash bulk-push-docs.sh --repos-file repos.txt --dry-run
#   bash bulk-push-docs.sh --repos-file repos.txt --pr   # crea PR en vez de push a main
#
# repos.txt — una ruta local por línea:
#   /Users/gasferna/mi-repo-1
#   /Users/gasferna/mi-repo-2
#   ...

set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

REPOS_FILE=""
DRY_RUN=false
CREATE_PR=false
BRANCH="chore/governance-bootstrap"
COMMIT_MSG="docs: governance bootstrap — Phase 0 analysis

Generated by Engineering Governance Framework.
Only docs-system/ files. No code changes."

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repos-file) REPOS_FILE="$2"; shift 2 ;;
    --dry-run)    DRY_RUN=true;    shift ;;
    --pr)         CREATE_PR=true;  shift ;;
    --branch)     BRANCH="$2";     shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

if [[ -z "$REPOS_FILE" || ! -f "$REPOS_FILE" ]]; then
  echo "Uso: bash bulk-push-docs.sh --repos-file repos.txt"
  echo ""
  echo "repos.txt — una ruta local de repo por línea"
  exit 1
fi

# ─── Resultados ───────────────────────────────────────────────────────────────

TOTAL=0
PUSHED=0
SKIPPED=0
FAILED=0
FAILED_REPOS=()

log()     { echo -e "${BLUE}[$repo_name]${NC} $*"; }
success() { echo -e "${GREEN}[$repo_name]${NC} $*"; }
warn()    { echo -e "${YELLOW}[$repo_name]${NC} $*"; }
err()     { echo -e "${RED}[$repo_name]${NC} $*"; }

# ─── Procesar cada repo ────────────────────────────────────────────────────────

while IFS= read -r repo_path || [[ -n "$repo_path" ]]; do
  # Ignorar líneas vacías y comentarios
  [[ -z "$repo_path" || "$repo_path" == \#* ]] && continue

  repo_path="${repo_path%/}"  # quitar trailing slash
  repo_name="$(basename "$repo_path")"
  TOTAL=$((TOTAL + 1))

  echo ""
  echo "────────────────────────────────────────────"
  echo "  [$TOTAL] $repo_name"
  echo "  $repo_path"
  echo "────────────────────────────────────────────"

  # Verificar que el repo existe
  if [[ ! -d "$repo_path" ]]; then
    err "Directorio no existe — saltando"
    FAILED=$((FAILED + 1))
    FAILED_REPOS+=("$repo_name — directorio no existe")
    continue
  fi

  # Verificar que es un repo git
  if [[ ! -d "$repo_path/.git" ]]; then
    err "No es un repositorio git — saltando"
    FAILED=$((FAILED + 1))
    FAILED_REPOS+=("$repo_name — no es repo git")
    continue
  fi

  # Verificar que docs-system/ existe
  if [[ ! -d "$repo_path/docs-system" ]]; then
    warn "docs-system/ no existe — saltando (ejecutar Phase 0 primero)"
    SKIPPED=$((SKIPPED + 1))
    continue
  fi

  # Verificar que hay algo para commitear
  cd "$repo_path"
  DOCS_CHANGES=$(git status --porcelain docs-system/ 2>/dev/null || true)

  if [[ -z "$DOCS_CHANGES" ]]; then
    warn "docs-system/ sin cambios pendientes — saltando"
    SKIPPED=$((SKIPPED + 1))
    continue
  fi

  log "Cambios encontrados en docs-system/:"
  git status --short docs-system/ | sed 's/^/  /'

  if [[ "$DRY_RUN" == "true" ]]; then
    log "[dry-run] Haría: git add docs-system/ → commit → push"
    PUSHED=$((PUSHED + 1))
    continue
  fi

  # Verificar rama actual
  CURRENT_BRANCH=$(git branch --show-current 2>/dev/null || echo "HEAD")
  log "Rama actual: $CURRENT_BRANCH"

  # Crear rama de governance si no existe
  if git show-ref --verify --quiet "refs/heads/$BRANCH" 2>/dev/null; then
    log "Rama $BRANCH ya existe — usando existente"
    git checkout "$BRANCH"
  else
    git checkout -b "$BRANCH"
    log "Rama $BRANCH creada"
  fi

  # Stagear solo docs-system/ — NADA más
  git add docs-system/

  # Verificar que no se está commiteando código por accidente
  STAGED=$(git diff --cached --name-only | grep -v "^docs-system/" || true)
  if [[ -n "$STAGED" ]]; then
    err "¡Archivos fuera de docs-system/ en el stage! Abortando:"
    echo "$STAGED" | sed 's/^/  /'
    git reset HEAD
    git checkout "$CURRENT_BRANCH"
    FAILED=$((FAILED + 1))
    FAILED_REPOS+=("$repo_name — archivos no-docs en stage")
    continue
  fi

  # Commit con GPG signing desactivado (evitar bloqueos en CI/scripts)
  GIT_CONFIG_COUNT=1 \
  GIT_CONFIG_KEY_0=commit.gpgsign \
  GIT_CONFIG_VALUE_0=false \
  git commit -m "$COMMIT_MSG" || {
    err "git commit falló"
    git checkout "$CURRENT_BRANCH"
    FAILED=$((FAILED + 1))
    FAILED_REPOS+=("$repo_name — commit falló")
    continue
  }

  if [[ "$CREATE_PR" == "true" ]]; then
    # Push de la rama y crear PR
    git push origin "$BRANCH" 2>/dev/null || git push --set-upstream origin "$BRANCH"

    if command -v gh &>/dev/null; then
      gh pr create \
        --title "docs: governance bootstrap — Phase 0 analysis" \
        --body "$(cat <<'EOF'
## Governance Bootstrap

Documentación generada por [Engineering Governance Framework](https://github.com/gefm2002/ai-engineering-governance) — Phase 0.

**Solo contiene archivos de `/docs-system/`. Sin cambios de código.**

### Qué incluye
- Estado actual del sistema documentado por el agente
- Flujos de negocio con criticidad (P0/P1/P2/P3)
- Arquitectura, integraciones, operaciones
- Deuda técnica y gaps identificados

### Cómo revisar
Leer `docs-system/00_INDEX.md` como punto de entrada.
EOF
)" \
        --base main 2>/dev/null && success "PR creado" || warn "PR ya existe o gh no disponible — rama pusheada"
    else
      warn "gh CLI no disponible — rama pusheada sin PR"
    fi

  else
    # Push directo a main
    git checkout main 2>/dev/null || git checkout master
    git merge "$BRANCH" --no-ff -m "docs: merge governance bootstrap for $repo_name"

    GIT_CONFIG_COUNT=1 \
    GIT_CONFIG_KEY_0=commit.gpgsign \
    GIT_CONFIG_VALUE_0=false \
    git push origin main 2>/dev/null || \
    git push origin master 2>/dev/null || {
      err "git push falló — puede requerir permisos o que la rama esté protegida"
      err "Intentar con --pr para crear PR en vez de push directo"
      FAILED=$((FAILED + 1))
      FAILED_REPOS+=("$repo_name — push a main falló")
      continue
    }
    success "docs-system/ pusheado a main"
  fi

  PUSHED=$((PUSHED + 1))

done < "$REPOS_FILE"

# ─── Resumen ──────────────────────────────────────────────────────────────────

echo ""
echo "════════════════════════════════════════════"
echo "  BULK PUSH — RESUMEN"
echo "════════════════════════════════════════════"
echo "  Total repos procesados: $TOTAL"
echo -e "  ${GREEN}Pusheados/PRs creados:${NC}  $PUSHED"
echo -e "  ${YELLOW}Salteados (sin cambios):${NC} $SKIPPED"
echo -e "  ${RED}Fallidos:${NC}               $FAILED"

if [[ ${#FAILED_REPOS[@]} -gt 0 ]]; then
  echo ""
  echo "  Repos con error:"
  for r in "${FAILED_REPOS[@]}"; do
    echo -e "    ${RED}✗${NC} $r"
  done
fi

echo "════════════════════════════════════════════"
echo ""
